In [2]:
import pandas as pd
import numpy as np


In [3]:
df = pd.read_csv('data/HW1-Data.csv')
df.head()

Student ID   Test1 Homeworks  Quizzes  Presentation Fianl-Exam
0        NaN  Max:50   Max:400  Max:140           NaN    Max:100
1        NaN     NaN       NaN      NaN           NaN        NaN
2         S1      41       244      136          50.0         90
3         S2      50       400      140          50.0        100
4         S3      43       327       88          50.0         79

In [4]:
# drop first 2 rows and start from index 0
df = df.drop(index=[0, 1])
df = df.reset_index(drop=True)
df.head()

Student ID Test1 Homeworks Quizzes  Presentation Fianl-Exam
0         S1    41       244     136          50.0         90
1         S2    50       400     140          50.0        100
2         S3    43       327      88          50.0         79
3         S4    43       336     123          50.0         35
4         S5    41       232     100          50.0         79

In [5]:
# drop Student ID since studentID = index + 1
df = df.drop(columns=['Student ID'])
df.head()

Test1 Homeworks Quizzes  Presentation Fianl-Exam
0    41       244     136          50.0         90
1    50       400     140          50.0        100
2    43       327      88          50.0         79
3    43       336     123          50.0         35
4    41       232     100          50.0         79

In [6]:
# convert all columns to float
for col in df.columns:
    df[col] = df[col].astype(float)

# Q1

## 1b. Get student reference ID

In [7]:
M_NUMBER_LAST_THREE_DIGITS = 830
STUDENT_REF_ID = (M_NUMBER_LAST_THREE_DIGITS % 26 ) + 4
print(f"Student Reference ID: {STUDENT_REF_ID}")

Student Reference ID: 28


## 1b. Standardize

In [8]:
# calculate mean and standard deviation
means = []
std_devs = []

for col in df.columns:
    mean = df[col].astype(float).mean()
    std_dev = df[col].astype(float).std()
    means.append(mean)
    std_devs.append(std_dev)

print("(*) Means and standard deviation of each column:")
for col, mean, std_dev in zip(df.columns, means, std_devs):
    print(f"    {col}: {mean:2.2f} ± {std_dev:2.2f}")

(*) Means and standard deviation of each column:
    Test1: 42.40 ± 6.36
    Homeworks: 291.47 ± 81.55
    Quizzes: 114.83 ± 20.94
    Presentation: 48.67 ± 3.46
    Fianl-Exam: 68.17 ± 22.89


In [9]:
# normalize data
df_normalized_1 = df.copy()
for i, col in enumerate(df_normalized_1.columns):
    df_normalized_1[col] = (df_normalized_1[col] - means[i]) / std_devs[i]
df_normalized_1.head()

Test1  Homeworks   Quizzes  Presentation  Fianl-Exam
0 -0.220111  -0.582062  1.010898       0.38564    0.953788
1  1.194886   1.330895  1.201934       0.38564    1.390638
2  0.094333   0.435729 -1.281533       0.38564    0.473254
3  0.094333   0.546092  0.390032       0.38564   -1.448885
4 -0.220111  -0.729213 -0.708425       0.38564    0.473254

In [10]:
# another way to normalize data using means and std_devs
df_normalized_2 = df.copy()
for col in df_normalized_2.columns:
    df_normalized_2[col] = (df_normalized_2[col]- df_normalized_2[col].mean()) / df_normalized_2[col].std()
df_normalized_2.head()

Test1  Homeworks   Quizzes  Presentation  Fianl-Exam
0 -0.220111  -0.582062  1.010898       0.38564    0.953788
1  1.194886   1.330895  1.201934       0.38564    1.390638
2  0.094333   0.435729 -1.281533       0.38564    0.473254
3  0.094333   0.546092  0.390032       0.38564   -1.448885
4 -0.220111  -0.729213 -0.708425       0.38564    0.473254

In [16]:
# print the row corresponding to your STUDENT_REF_ID
print(f'Student Reference ID: {STUDENT_REF_ID}, index: {STUDENT_REF_ID-1}\n')
print(f'Original DataFrame:\n{df.iloc[STUDENT_REF_ID-1]}\n')
print(f'Normalized DataFrame:\n{df_normalized_1.iloc[STUDENT_REF_ID-1]}')

Student Reference ID: 28, index: 27

Original DataFrame:
Test1            45.0
Homeworks       392.0
Quizzes         130.0
Presentation     50.0
Fianl-Exam       77.0
Name: 27, dtype: float64

Normalized DataFrame:
Test1           0.408777
Homeworks       1.232795
Quizzes         0.724345
Presentation    0.385640
Fianl-Exam      0.385884
Name: 27, dtype: float64


## 1g. covariance matrix

In [19]:
# get the covariance matrix of the normalized data
cov_matrix = df_normalized_1.cov()
cov_matrix

Test1  Homeworks   Quizzes  Presentation  Fianl-Exam
Test1         1.000000   0.528216  0.528979      0.589584    0.310255
Homeworks     0.528216   1.000000  0.433183      0.492705    0.123313
Quizzes       0.528979   0.433183  1.000000      0.587463    0.284523
Presentation  0.589584   0.492705  0.587463      1.000000    0.312244
Fianl-Exam    0.310255   0.123313  0.284523      0.312244    1.000000

## 1h. Eigenvectors and eigenvalues

In [20]:
# find eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")    
print(eigenvectors)

Eigenvalues:
[2.74013034 0.89489394 0.54782139 0.3910074  0.42614693]

Eigenvectors:
[[-0.49842442 -0.06846767 -0.18547916 -0.45846469 -0.70872624]
 [-0.4330442  -0.44889039 -0.61155673  0.03462762  0.48556093]
 [-0.47655198 -0.0216836   0.66377748 -0.3951545   0.41914247]
 [-0.5040327  -0.03452812  0.25079718  0.79526868 -0.22227764]
 [-0.28791502  0.89002653 -0.29680983  0.00342098  0.19196337]]


# Q2